### ISSUE TITLE
I don't know why, but the program crashes after starting the download.

### ISSUE THREAD

**Issue by CryCitty** [BrandenStoberReal/PartyLib#10]
win11 23H2 7950X3D 32G RAM
like this👇
https://img94.pixhost.to/images/1004/459779453_0045345211.gif
<a href="https://img94.pixhost.to/images/1004/459779453_0045345211.gif"><img src="https://t94.pixhost.to/thumbs/1004/459779453_0045345211.gif" alt="0045345211.gif" border="0"/></a>

**Comment by CryCitty** [comment]
![Uploading 0045345211.gif…]()
![Uploading 0045345211.gif…]()

**Comment by BrandenStoberReal** [comment]
Hey!

A rewrite is currently in process utilizing an entirely new backend. That appears to be the legacy GUI, and is extremely unstable/deprecated. I ask that you be patient while I slowly implement the new backend.

**Comment by BrandenStoberReal** [comment]
I am closing this issue. If it persists on the new module backend, please create a new issue once it is released.
